// AUTO-GENERATED by scripts/refresh_retailers.py. Curated inputs live in data/retailer-sources.json.
export type ShopSuggestion = {
  id: string;
  retailer: string;
  name: string;
  category: "shirt" | "overshirt" | "trousers" | "shorts" | "shoes";
  colour: string;
  priceLabel: string;
  match: number;
  pairsWith: string[];
  reason: string;
  href: string;
  sourceType: "product" | "category";
  checkedAt: string;
  sale?: string;
  imageUrl?: string;
  imageAlt?: string;
  availability?: string;
  productCode?: string;
  refreshStatus?: "live" | "stale" | "manual";
  lastAttemptAt?: string;
};

export const shopSuggestions: ShopSuggestion[] = [
  {
    id: "next-stone-tapered-chinos",
    retailer: "NEXT",
    name: "Stone Regular Tapered Fit Stretch Chinos",
    category: "trousers",
    colour: "Stone",
    priceLabel: "€32",
    match: 97,
    pairsWith: ["grey-linen-shirt", "white-textured-shirt", "cream-pocket-tee", "adidas-white-black"],
    reason: "Stone trousers are the most useful missing bridge between your white/cream shirts and darker tops. They recreate several of your saved smart-casual references without becoming formal.",
    href: "https://www.next.ie/en/style/st525777/ag4042",
    sourceType: "product",
    checkedAt: "2026-09-02",
    availability: "Refresh unavailable; open NEXT to verify current stock",
    productCode: "AG4-042",
    imageUrl: "https://xcdn.next.co.uk/common/items/default/default/itemimages/3_4Ratio/product/lge/AG4042s.jpg",
    imageAlt: "NEXT stone tapered fit chinos",
    refreshStatus: "stale",
    lastAttemptAt: "2026-09-05T09:07:21Z"
  },
  {
    id: "hm-black-relaxed-shorts",
    retailer: "H&M",
    name: "Relaxed Fit Shorts",
    category: "shorts",
    colour: "Black",
    priceLabel: "€29.99",
    match: 96,
    pairsWith: ["grey-linen-shirt", "white-textured-shirt", "puma-white-green"],
    reason: "This is the closest ready-made version of the relaxed dark-short silhouette already visible in your outfits. It keeps the look clean rather than sporty.",
    href: "https://www2.hm.com/en_ie/productpage.1265992001.html",
    sourceType: "product",
    checkedAt: "2026-09-02",
    availability: "Refresh unavailable; open H&M to verify current stock",
    productCode: "1265992001",
    refreshStatus: "stale",
    lastAttemptAt: "2026-09-05T09:07:21Z"
  },
  {
    id: "zara-white-linen-shirt",
    retailer: "Zara",
    name: "100% Linen Regular Fit Shirt",
    category: "shirt",
    colour: "White",
    priceLabel: "€45.95",
    match: 95,
    pairsWith: ["grey-jeans", "black-jeans", "olive-cargo", "adidas-white-black"],
    reason: "Your strongest repeated look is a breathable light shirt with a relaxed collar and rolled sleeves. This current Zara linen shirt is a direct extension of that pattern.",
    href: "https://www.zara.com/ie/en/100-linen-regular-fit-shirt-p01063410.html",
    sourceType: "product",
    checkedAt: "2026-09-05",
    availability: "Product page reachable at Zara when refreshed",
    productCode: "1063/410/250",
    imageAlt: "Zara 100% Linen Regular Fit Shirt",
    refreshStatus: "live",
    lastAttemptAt: "2026-09-05T09:07:21Z"
  },
  {
    id: "uniqlo-cotton-linen-shirt-jacket",
    retailer: "UNIQLO",
    name: "Cotton Linen Blend Shirt Jacket",
    category: "overshirt",
    colour: "Beige / Natural",
    priceLabel: "€29.90",
    sale: "Reduced from €49.90 when checked",
    match: 94,
    pairsWith: ["white-tee", "grey-jeans", "black-jeans", "puma-white-green"],
    reason: "A lightweight natural overshirt gives you the same easy layering effect as your current cream and beige pieces without becoming too formal.",
    href: "https://www.uniqlo.com/eu-ie/en/products/E482443-000/00?colorDisplayCode=69",
    sourceType: "product",
    checkedAt: "2026-09-05",
    availability: "Product page reachable at UNIQLO when refreshed",
    productCode: "482443",
    imageUrl: "https://image.uniqlo.com/UQ/ST3/eu/imagesgoods/482443/item/eugoods_57_482443_3x4.jpg",
    imageAlt: "UNIQLO cotton linen blend shirt jacket",
    refreshStatus: "live",
    lastAttemptAt: "2026-09-05T09:07:21Z"
  },
  {
    id: "zara-relaxed-trousers",
    retailer: "Zara",
    name: "Relaxed Fit Pleated / Linen Trousers",
    category: "trousers",
    colour: "Charcoal / Stone",
    priceLabel: "from €35.95",
    match: 93,
    pairsWith: ["white-textured-shirt", "grey-linen-shirt", "cream-pocket-tee", "adidas-white-burgundy"],
    reason: "A slightly fuller charcoal or stone trouser preserves your dark-bottom preference while giving the silhouette more polish than denim.",
    href: "https://www.zara.com/ie/en/man-trousers-l838.html",
    sourceType: "category",
    checkedAt: "2026-09-05",
    availability: "Current Zara range; category link refreshed",
    refreshStatus: "manual",
    lastAttemptAt: "2026-09-05T09:07:21Z"
  },
  {
    id: "cos-beige-overshirt",
    retailer: "COS",
    name: "Contrast-Panel Cotton Overshirt",
    category: "overshirt",
    colour: "Beige",
    priceLabel: "€129",
    match: 92,
    pairsWith: ["white-tee", "black-jeans", "grey-jeans", "adidas-white-black"],
    reason: "The relaxed beige utility shape fits directly into your existing neutral layering system and is more refined than adding another graphic layer.",
    href: "https://www.cos.com/en-ie/men/menswear/shirts/cottonshirts/product/contrast-panel-cotton-overshirt-beige-1326530001",
    sourceType: "product",
    checkedAt: "2026-09-02",
    availability: "Refresh unavailable; open COS to verify current stock",
    productCode: "1326530001",
    refreshStatus: "stale",
    lastAttemptAt: "2026-09-05T09:07:21Z"
  },
  {
    id: "mango-linen-shirt",
    retailer: "MANGO",
    name: "Regular-fit 100% Linen Shirt",
    category: "shirt",
    colour: "Natural / Sand",
    priceLabel: "€40.00",
    sale: "33% off when checked",
    match: 90,
    pairsWith: ["grey-jeans", "black-jeans", "light-grey-denim-shorts", "timberland-brown"],
    reason: "Mango's linen shirt gives you the same relaxed shirt language with a slightly cleaner, more grown-up finish.",
    href: "https://shop.mango.com/ie/en/p/men/shirts/linen/regular-fit-100-linen-shirt/27085939/57/00",
    sourceType: "product",
    checkedAt: "2026-09-05",
    availability: "Product page reachable at MANGO when refreshed",
    productCode: "27085939",
    imageUrl: "https://media.mango.com/is/image/punto/27085939-57-002?wid=1024",
    imageAlt: "MANGO Regular-fit 100% Linen Shirt",
    refreshStatus: "live",
    lastAttemptAt: "2026-09-05T09:07:21Z"
  },
];
